### ISSUE TITLE
Use of os.system for Windows Clipboard

### ISSUE THREAD

**Issue by KillerInstinct** [kennyhml/ark-gacha-bot#2]
There are two places in the repo ([here](https://github.com/kennyhml/ark-gacha-bot/blob/cad9e72bb3091a2a6832daada52126b99726e10f/bot/ark_bot.py#L143) and [here](https://github.com/kennyhml/ark-gacha-bot/blob/cad9e72bb3091a2a6832daada52126b99726e10f/ark/inventories/inventory.py#L255)) which use os.system() to pass some input to `| clip`; This is generally frowned upon for reasons of potential command injection (limited risk in the use of this repo, from what I can tell) and in general unneeded overhead of spawning a process.

I would recommend using win32clipboard (from pywin32) or another similar library.

```python
import win32clipboard  # from pypiwin32 / pywin32


def set_clipboard(text: str = ""):
    win32clipboard.OpenClipboard()
    win32clipboard.EmptyClipboard()
    win32clipboard.SetClipboardText(text, win32clipboard.CF_TEXT)
    win32clipboard.CloseClipboard()
```

**Comment by kennyhml** [comment]
While there really wasnt much of a risk concerning this repo, I have changed it to using win32clipboard (as I need pywin32 anyways). Thanks for pointing this out, the original os code was from stackoverflow and it had not been noted there.
